name: Build Test and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_execute_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Execute unit tests
        run: npm run test:unit
      - name: Display softuni username
        run: echo 'Embarata'

  Execute_UI_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Install browsers
        run: npx playwright install
      - name: Run application
        run: npm start &
      - name: Execute UI tests
        run: npm run test:ui
